### ISSUE TITLE
Reservering weghalen na het uitlenen van een reservering. Update status Reservering

### ISSUE THREAD

**Issue by PJEilers** [PJEilers/WTLibraryApp#93]

**Comment by HuubV** [comment]
Hoe bedoel je?

**Comment by PJEilers** [comment]
Dat nadat een reservering van een boek is toegekend aan iemand (uitgeleend), dat het niet meer zichtbaar is in de reserveringslijst. Misschien niet verwijderen uit de database, maar een status veld aan de reservering toevoegen oid.

**Comment by HuubV** [comment]
ah duidelijk
